name: 'Cache Rounds'
description: Cache Rounds installation'
outputs:
  cache-hit:
    value: ${{ steps.cache-rounds.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Get ROUNDS version id
      id: rounds-version
      shell: pwsh
      run: echo "version=$((Invoke-WebRequest -URI https://api.steamcmd.net/v1/info/1557740).Content | jq -r '.data."""""1557740""""".depots.branches.public.buildid')" >> $GITHUB_OUTPUT

    - name: Cache ROUNDS
      id: cache-rounds
      uses: actions/cache@v2
      with:
        path: $GITHUB_WORKSPACE/rounds_install
        key: ROUNDS-${{ steps.rounds-version.outputs.version }}