name: Run tests

on: push

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get ROUNDS version id
        id: roundsversion
        run: echo "::set-output name=roundsversion::$(curl -s https://api.steamcmd.net/v1/info/1557740 | jq -r ".data.\"1557740\".depots.branches.public.buildid")"

      - name: Cache ROUNDS
        id: cacherounds
        uses: actions/cache@v2
        with:
          path: ~/ROUNDS_INSTALL
          key: ROUNDS-${{ steps.roundsversion.outputs.roundsversion }}

      - name: Install SteamCMD
        if: steps.cacherounds.outputs.cache-hit != 'true'
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Install ROUNDS
        if: steps.cacherounds.outputs.cache-hit != 'true'
        run: |
          steamcmd +@sSteamCmdForcePlatformType windows +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +force_install_dir ~/ROUNDS_INSTALL +app_update 1557740 validate +exit

      - name: Prepare MapsExtended dependencies
        run: |
          wget -O bepinex.zip "https://thunderstore.io/package/download/BepInEx/BepInExPack_ROUNDS/5.4.1900/"
          unzip bepinex.zip -d ~/BepInExRaw
          mv ~/BepInExRaw/BepInExPack_ROUNDS/* ~/ROUNDS_INSTALL/

          wget -O mmhook.zip "https://thunderstore.io/package/download/willis81808/MMHook/1.0.0/"
          unzip mmhook.zip -d ~/ROUNDS_INSTALL/BepInEx/plugins/mmhook

          wget -O unboundlib.zip "https://thunderstore.io/package/download/willis81808/UnboundLib/3.2.10/"
          unzip mmhook.zip -d ~/ROUNDS_INSTALL/BepInEx/plugins/unboundlib/

      - name: Create Config.props
        run: |
          echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><Project ToolsVersion=\"Current\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\"><PropertyGroup><RoundsDir>$HOME/ROUNDS_INSTALL</RoundsDir><BepInExDir>$HOME/ROUNDS_INSTALL/BepInEx</BepInExDir></PropertyGroup></Project>" > Config.props
      
      - name: Build and test
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        run: |
          dotnet restore
          dotnet tool restore
          dotnet build
          dotnet surity "$HOME\ROUNDS_INSTALL\Rounds.exe" --filter-stacktraces "FluentAssertions.* | Surity.*" --compact-stacktraces
